### ISSUE TITLE
The promotional footer

### ISSUE THREAD

**Issue by bep** [themefisher/timer-hugo#1]
Hey,

I'm the lead developer in Hugo. You make great looking themes, but the "Buy more themes" in the footer is stretching the attribution requirement in the CCA license a little too far:

Ref. https://github.com/themefisher/timer-hugo/blob/master/layouts/partials/footer.html#L11

I understand that you want to make money from these, but I would still ask you to revise this footer and make it less promotional. It would good if you could do that for all of your themes that is listed on https://themes.gohugo.io/

/cc @digitalcraftsman @onedrawingperday

**Comment by mehedi-sharif** [comment]
Hello Pedersen,
Its a pleasure to meet with you . As we convert this them from our existing bootstrap template we did not notice that. I am going to update the footer right now. But you asked to change the footer from all of my template. As far as I know in my other templates the footer text is “Design and developed by themefisher” . Can I use this text ? In a reference https://themes.gohugo.io/theme/forty/ this template has also a credit . If you can give me suggestion I will obviously collaborate with you .
Thanks

**Comment by bep** [comment]
Designed by etc. with link is of course fine.

**Comment by mehedi-sharif** [comment]
We made an update. can you please check it out.
