### ISSUE TITLE
Timer-Hugo: Change Tile Order of Portfolio section on the front page

### ISSUE THREAD

**Issue by pickardpredictives** [themefisher/timer-hugo#11]
How do I change the order in which the tiles appear in the portfolio section of my front page?

**Comment by mehedi-sharif** [comment]
the section you want to put first - copy that code and paste at the top. 
thats it .

**Comment by pickardpredictives** [comment]
Sorry, I should've included more information.

This is what it looks like on my website. I want to reorder the 6 tiles in
this portfolio section.
[image: image.png]
There's a markdown (.md) file for each tile in the ./content/portfolio
section that controls what's on the tile as well as the page each tile is
linked to.  But I don't see where I can re-order the tiles.

I've tried renaming the files in the portfolio folder like this:
[image: image.png]

But that doesn't work.  There's no portfolio section in the config.toml
file, so I can't rearrange it there.

So, if it's a matter of copy and pasting to rearrange the order, what file
is that in?

**Comment by mehedi-sharif** [comment]
Can you please give me some images to point what you want or use 
https://chrome.google.com/webstore/detail/loom-video-recorder-scree/liecbddmkiiihnedobmlmillhodjkdmb?hl=en-US
This extention to record your issue and give me the link .
Thanks

**Comment by Christian1313** [comment]
Can i reopen?

How do i define the order of the portfolio elements?
