### ISSUE TITLE
How can I add disqus to the blog page?

### ISSUE THREAD

**Issue by manwar** [themefisher/timer-hugo#12]
Is it possible to simply plug-in disqus to each blog page?

https://help.disqus.com/installation/add-disqus-to-static-pages-in-blogger

**Comment by mehedi-sharif** [comment]
We did not try it before . But I think its possible.

**Comment by manwar** [comment]
Could you please show us how to?

**Comment by Somrat37** [comment]
Hey @manwar,
[Here](https://gohugo.io/content-management/comments/) is a great documentation for add disqus on your blog page.
