### ISSUE TITLE
markdown in content ? 

### ISSUE THREAD

**Issue by nkirsch** [themefisher/timer-hugo#13]
I apologize if this is a hugo thing and not a `timer-hugo` thing, but I don't appear to be able to use markdown in the `content` directive in `config.toml`

e.g.

```
[params.input]
     content = """
Here's some **very** important markdown.

This is *less* important...
"""
```

`GitHub`:

Here's some **very** important markdown.

This is *less* important...

`timer-hugo`:

`Here's some **very** important markdown. This is *less* important...`

Happy to try whatever.

**Comment by Somrat37** [comment]
hey there, i check your issue in localhost. and markdown are working perfectly in content.
