### ISSUE TITLE
[params.featureProduct] in config does not have any effect

### ISSUE THREAD

**Issue by appernetic** [themefisher/timer-hugo#16]
In config.toml there is [params.featureProduct] and no related section in the front page.

In partials there is feature.html that has {{ if .Site.Data.feature.enable }}

Can it be that the feature.html partial should have the {{ if .Site.Params.feature.enable }} and in the config.toml it should be {{ if .Site.Params.feature.enable }}

**Comment by Somrat37** [comment]
hey @appernetic , there was a mistake. i just cleaned this extra line of code. thanks
