### ISSUE TITLE
Your link to documentation does not work on the README file.

### ISSUE THREAD

**Issue by appernetic** [themefisher/timer-hugo#22]
Your link to documentation does not work on the README file.

**Comment by Somrat37** [comment]
hey @appernetic , i checked this template in localhost, and all the pages working correctly, but i don't know why it's not working on hugo demo server. you can download and serve this template for all pages.

**Comment by pickardpredictives** [comment]
I think @appernetic  was talking about the link on the github respository.  When you click on it the link under the Installation section, the page can't be found.

**Comment by ksymer** [comment]
I agree that this is not fixed. 

The link on the github repo homepage generated by the readme file, or https://github.com/themefisher/timer-hugo/blob/master/README.md, "Full Documentation." points to https://themes.gohugo.io/theme/timer-hugo/blog/installation/, which is 404. Screenshot of relevant section:

![image](https://user-images.githubusercontent.com/46517927/60736535-30e13400-9f0c-11e9-84e7-bb6bfd1dca7a.png)

If you go up one folder level on the demo site to /blog, which forwards to https://themes.gohugo.io//theme/timer-hugo/post/, you see some documentation-related blog posts. But nothing about installation as implied. Is there another file or should that link be removed from the docs entirely?

On a related note, the hugo timer demo's main navigation does not work. Pages are 404, which makes it difficult to view the examples. I have been visiting the non-hugo timer demo to find what I need. Maybe others will find this link helpful: http://demo.themefisher.com/themefisher/timer/
