### ISSUE TITLE
New Single Page - Embed an iFrame

### ISSUE THREAD

**Issue by mpfp** [themefisher/timer-hugo#23]
Hi,

Nice template.  Thanks for creating it.

I'm trying to add a new menu item with a page that uses an iframe to embed a calendar from another website. Here is what I've done:

1. Added the menu item to my config.toml:

`    [[menu.nav]]`
`        name    = "Course Schedule"`
`        url     = "/trainings"`
`        weight  = 2`

2. Created a "trainings" folder under "content".

3. Added a "_index.md" file in the "trainings" folder. It contains the following:

`---`
`title: Upcoming Trainings`
`author: Matt Pickard`
`date: '2019-05-23'`
`url: /trainings/`
`---`

`<iframe url = "https://www.supersaas.com/schedule/ppllc/PPLLC_Training"></iframe>`

But the iframe does not show up in the generated html file. 

Can you give me guidance on how to appropriately do this with the timer-hugo theme, please? It's not clear whether I should be treating this as a "post" or creating a new template under the theme's "layout" folder.

Any help would be appreciated.

**Comment by Somrat37** [comment]
Hey @mpfp ,
I got your problem.  u want to show another website in your site. You should create a folder in layout folder with the same name you have created in content folder. now create a list.html file in this folder. and call header,  page-title and footer partial.  then after page title partial just copy `<iframe src="https://www.supersaas.com/schedule/ppllc/PPLLC_Training"></iframe>` this line of code and paste there. now save it. and you will get your result.
