### ISSUE TITLE
Adapting the "timer" error message (form validation) to "navigator" theme

### ISSUE THREAD

**Issue by divinerites** [themefisher/timer-hugo#25]
Hello,

I have both premium timer-hugo and navigator-hugo.

- I'm trying to adapt the form from this Timer theme to my Navigator theme (removing the php part and using netlify) : This works just fine.
- I as trying to mimic (in Navigator) the form control from Timer but i have a css problem I guess, but i'm working in circles with this.

1. Add the plug-in `form-validator` as in Timer theme
```
<script src="{{ "plugins/form-validation/jquery.form.js" | relURL }}"></script>
<script src="{{ "plugins/form-validation/jquery.validate.min.js" | relURL }}"></script>
````
2. Add the .css part  stolen from Timer theme.
```css
.error {
  padding: 10px;
  color: blue; /* #D8000C; */
  border-radius: 2px;
  font-size: 14px;
  background-color: #FFBABA;
}

.success {
  background-color: #6cb670;
  border-radius: 2px;
  color: #fff;
  font-size: 14px;
  padding: 10px;
}
```

3. Add this javascript (stolen from Timer)

```js
$('#contact-form').validate({
        rules: {
            name: {
                required: true,
                minlength: 4
            },
            email: {
                required: true,
                email: true
            },
            subject: {
                required: false,
            },
            message: {
                required: true,
            },
        },
        messages: {
            user_name: {
                required: "Come on, you have a name don't you?",
                minlength: "Your name must consist of at least 2 characters"
            },
            email: {
                required: "Please put your email address",
            },
            message: {
                required: "Put some messages here?",
                minlength: "Your name must consist of at least 2 characters"
            },
        }
    });
````

But I do not succeed to get the error message **below** the text box. It is always **on** the text box in my Navigator theme

<img width="570" alt="Capture d’écran 2019-06-25 à 15 35 17" src="https://user-images.githubusercontent.com/32342823/60103464-efa89180-975f-11e9-9ce5-ea7b63f8836f.png">

But should look like this (this is from my Timer theme)

<img width="525" alt="Capture d’écran 2019-06-25 à 15 35 50" src="https://user-images.githubusercontent.com/32342823/60103579-25e61100-9760-11e9-88c1-8c2a6d60af80.png">

I'm pretty sure I miss something obvious, so any tip/help/advice/direction will be appreciated.

**Comment by divinerites** [comment]
1 - This is the **wrong** HTML code (from timer) :

```html
<div class="form-group">
       <input type="text" placeholder="Votre Nom" class="form-control error" name="name" id="name"> 
       <label for="name" class="error" style="display: inline-block;">Please enter at least 4 characters. 
       </label>
</div>
```

2 - This is the **working** HTML code (from navigator)

```html
<div class="form-group wow fadeInDown animated" data-wow-duration="500ms" data-wow-delay=".6s" style="visibility: visible; animation-duration: 500ms; animation-delay: 0.6s; animation-name: fadeInDown;">
   <input type="text" placeholder="Votre Nom" class="form-control error" name="name" id="name"> 
    <label for="name" class="error">Please enter at least 4 characters.</label>
</div>
```

**Comment by Somrat37** [comment]
Hey @divinerites , i understand your problem, but i can't fix it without see your whole code. if you hosted this template anywhere then give me the link that i can inspect this code and fixed that issue, or send me the whole template as a zip, i will fix it.

**Comment by divinerites** [comment]
Repo is private on GitHub (divinerites/camping-arolla-navigator) 

I invited you and my code is on the "Controle-formulaire branch).

Thanks in advance

**Comment by Somrat37** [comment]
hey @divinerites , i just fixed your issue and make a push, can you please check. if anything goes wrong let me know.

**Comment by divinerites** [comment]
Thanks a lot, I didn't realize it was done with a simple bootstrap style `d-block`.

Thanks A LOT for your reactivity !!!! And give my best regards to Mehedi, you have mage such great great themes !!!
