### ISSUE TITLE
How to change default home page?

### ISSUE THREAD

**Issue by Kundan22** [themefisher/timer-hugo#26]
I want to change the default home page to **http://website.com/blog** when users hit **http://website.com**
where should I change?

**Comment by Somrat37** [comment]
hey @Kundan22 , Default homepage are rendered from `index.html` file, and the blog page came from `default/list.html` file. you can create a partial from the list.html file, and call it in the index.html file.

**Comment by Kundan22** [comment]
It works. Thanks
