### ISSUE TITLE
found no layout file for "HTML" for "home": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.

### ISSUE THREAD

**Issue by tmyngu11** [themefisher/timer-hugo#27]
on a new clean site, it gives this error when running hugo start using the example site

I copied examplesite files over to root with no changes

WARN 2019/08/09 02:09:40 found no layout file for "HTML" for "home": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.

results in a blank white page when visiting localhost:1313

**Comment by yannick9906** [comment]
Are you sure to run the hugo server command from the root folder? I did the mistake to run the command from within the themes folder, then I got the same error.
