### ISSUE TITLE
Text decoration

### ISSUE THREAD

**Issue by Lo-boom** [themefisher/timer-hugo#30]
Hi, 
I use Typora and Atom to change the theme and the content. Now I have seen that the theme dosen't accept any text decorations like ** ** for bold or <b>bold</b>. Is there a way to change it? 
Thank you for your help.

**Comment by divinerites** [comment]
You have to be more specific or share a Git repo. 
I use it every day and markdown `.md` files in the blog section are processed perfectly.

**Comment by divinerites** [comment]
and if in other sections, just check if your template use `{{ .Content | markdownify }}`

**Comment by Lo-boom** [comment]
![image](https://user-images.githubusercontent.com/43420836/68090132-8b65af00-fe70-11e9-8ccc-78e1f157e043.png)
--> Typora: enable  : true
title   : Why We are Different
description: >
  Nous sommes une **micro-association**
It is a .yml file, as in the exemple site of the theme

**Comment by divinerites** [comment]
I told you above : you have to check if it uses `markdownify` in the desired section.

In your case in `about/list.html` you should fork the template and use 

`{{ with .description }}<p>{{ . | markdownify }}</p>{{ end }}`

**Comment by Lo-boom** [comment]
Ok
So that's the result with {{ end }} at the end
![image](https://user-images.githubusercontent.com/43420836/68090447-257b2680-fe74-11e9-8a3f-bcb54be261d4.png)
Without {{ end }}:
![image](https://user-images.githubusercontent.com/43420836/68090462-53f90180-fe74-11e9-958f-446320f88f47.png)
I don't know why the text appaers two times.

**Comment by divinerites** [comment]
you have to share a repo. it's impossible to guess like that

**Comment by divinerites** [comment]
And a good practice is **not** to change the theme directly.

**Comment by Lo-boom** [comment]
Thank you for your help. I dont know what is a repo. My english is not well as you can read it.
Will take another easier theme :)

**Comment by divinerites** [comment]
il faut que tu partage un dépot (github par exemple) et comme cela on peut aller voir ce qui se passe. Comme cela c'est impossible de savoir ce qui est changé et ce qui se passe.

Regarde du coté de https://gohugo.io/hosting-and-deployment/hosting-on-github/

**Comment by divinerites** [comment]
le problème n'est pas le theme. Il est **très bien** conçu.
Il faut que tu comprenne un minimum de la philosophie de gohugo.io. Tu auras les même pbs sur d'autres thèmes

**Comment by Lo-boom** [comment]
Je ne critique en aucun cas le theme ;) Je me demandais juste pourquoi on ne pouvait pas utiliser les text decoration à certains endroits. J'ai déjà utilisé d'autres theme pour d'autres site et jamais eu de problème pour les modifier. 
Demain je verrai pour le partage d'un dépot.

**Comment by Lo-boom** [comment]
Salut, Vooilà, j'ai retéléchargé le theme sans le modifier à part d'ajouter:

> {{ with .Site.Data.about.description }}{{ . | markdownify }} dans about/ list.html. 
Cela fonctionne mais le text apparait en double. 

![image](https://user-images.githubusercontent.com/43420836/68118010-345aeb00-feff-11e9-82c0-72c4a6b73bbc.png)
![image](https://user-images.githubusercontent.com/43420836/68118045-489ee800-feff-11e9-82b3-1d09884d43cd.png)
![image](https://user-images.githubusercontent.com/43420836/68118076-594f5e00-feff-11e9-864e-68b913c3f288.png)

**Comment by divinerites** [comment]
You have a duplicate of '.' One with markdownify and one with safehtml.
