### ISSUE TITLE
Layout problem in Netlify

### ISSUE THREAD

**Issue by christopherisnow** [themefisher/timer-hugo#32]
I recently installed timer-hugo in a Git-hosted website to deploy with Netlify. In contrast to the one-click Hugo on Netlify dummy theme, which looks fine, building the Timer theme gives me what seems to be raw HTML: https://5df36fba1873d0a06d766551--gracious-franklin-74587b.netlify.com/index.html

No errors from the Netlify console.

Could this be a theme-related problem, some incompatibility with the etlify backend?

The full site repo is here for reference: https://github.com/christopherisnow/jadiweb

Thanks in advance.

**Comment by divinerites** [comment]
First, you have to change baseurl in config.toml with the real url in
production

Then add a netlify.toml to Help an expected behaviour

Le ven. 13 déc. 2019 à 19:48, christopherisnow <notifications@github.com> a
écrit :

**Comment by christopherisnow** [comment]
Thanks @divinerites. I followed both your tips but I still get the same result. 

I also reinstalled the theme as a submodule according to [Hugo's Netlify instructions](https://gohugo.io/hosting-and-deployment/hosting-on-netlify/).

Is there something missing from the netlify.toml?:

`[build]
  publish = "public"
  command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.58.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  
[context.branch-deploy.environment]
  HUGO_VERSION = "0.58.0"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.58.0"
  
[context.deploy-preview]
  command = "hugo -b $DEPLOY_PRIME_URL --buildFuture"

[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL --buildFuture"
`

**Comment by christopherisnow** [comment]
Spoke too soon -- it looks correct now! Base URL seems to have been the problem :)
