### ISSUE TITLE
Can't seem to add flickr as an icon

### ISSUE THREAD

**Issue by thirdletter** [themefisher/timer-hugo#36]
Hi,

Looking through the ionicons database, I found an entry for a flickr icon I'd like to use.
Unfortunately I cannot find the accurate icon path to add it to the list.
I tried this:
[[params.socialIcon]]
icon = "ion-logo-flickr"
url = "#"

[[params.socialIcon]]
icon = "logo-flickr-outline"
url = "#"

Neither of those seem to work. How do I add flickr to the list of available icons? if it's a case of just not knowing the name of the flickr icon, how do I find/add those?

**Comment by themefisherDev** [comment]
I am sorry to say that we used ionicon v2.00, that does not have flickr icon. We will update this icon pack soon...
