### ISSUE TITLE
Best Place for Google Analytics Template

### ISSUE THREAD

**Issue by Sawrz** [themefisher/timer-hugo#37]
Hi,
I want to add analytics to my page. However, I'm searching the right spot to add the template from Hugo for Google Analytics. 
I thought about the partial "header.html" since it's on every site, but I may be wrong. 
Can you provide me some instructions on where the best spot would be? And another more general question: Do I need both templates, so the asynchronous as well?

Thanks,
Sandro

**Comment by themefisherDev** [comment]
Hey, You can add those templates in the header file.  and yes! you should add both of those templates.

**Comment by Sawrz** [comment]
Hey, 
recently, I found the following code in the footer.html:
```
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    ga('create', '{{ .Site.Params.googleAnalitycsID }}', 'auto');
    ga('send', 'pageview');
</script>
```
So, isn't that already what the templates from hugo would add? Just to make sure there are no unneccesary calls for the analytics script.

**Comment by themefisherDev** [comment]
It has builtin google analytics, you simply put your id in config.toml file. of you can remove it if you want to use hugo google analytics internal template.
