### ISSUE TITLE
Drop down menus

### ISSUE THREAD

**Issue by Resonanz** [themefisher/timer-hugo#4]
Hi. Any thoughts on how to do drop down menus? Here is a header partial from a Hugo Bootstrap 4 (I think) theme:

https://github.com/bul-ikana/hugo-cards/blob/master/layouts/partials/header.html

**Comment by Resonanz** [comment]
This dropdown code definitely comes from Bootstrap 4:

https://github.com/Xzya/hugo-bootstrap/blob/master/layouts/partials/header.html

**Comment by mehedi-sharif** [comment]
Hey @Resonanz ,
Basically to build hugo dropdown menu not the same way what bootstrap does . In next release we will add dropdown menu in timer .
Thanks
