### ISSUE TITLE
Email contact

### ISSUE THREAD

**Issue by PierfraFerro** [themefisher/timer-hugo#40]
Hello to everybody,

I'm using Timer Theme for my static Hugo site, but I don't undertand where I have to put the mail to use in the contact form.
Any suggestions?

Thanks for your help.

**Comment by Somrat37** [comment]
Hey there, please take a pull first, then you will find a variable is config.toml file called `contactFormAction`, then put your form action there. thanks

**Comment by Somrat37** [comment]
Did you solve your problem? I am going to close this issue, if you need more help, don't hesitate to reopen this issue.
