### ISSUE TITLE
Example Site content missing for About Service Gallery pages

### ISSUE THREAD

**Issue by damien1** [themefisher/timer-hugo#42]
Hi

I've installed the theme and love it - looking at the demo site I can see pages for About, Service and Gallery

but this is missing from the examplesite content folder 

Can you give me some instructions or example on how to create markdown content for these content types please

thanks.

**Comment by divinerites** [comment]
Those sections do not use markdown files, but `Data` files in `/data/service.yml` or `/data/about.yml` for example.
