### ISSUE TITLE
Word-wrap on animated slider

### ISSUE THREAD

**Issue by HiddeSmit** [themefisher/timer-hugo#49]
I would like to get word wrapping working on the animated slider (params.banner.flipText).
If the text is more than 3 words, it doesn't fit on screen for mobile devices.

Been tinkering away on 'cd-words-wrapper' in style.css and I've been fumbling around with slider.css as well.
But I just can't get it to wrap.

I tried adding markdownify in the banner.html to try and introduce line-breaks, to no avail.

**Comment by HiddeSmit** [comment]
Adding `<br>` in the config.toml and than adding `| safeHTML` to the `.title` in banner.html helps.
However dynamic wrapping based on viewport would be better.

**Comment by developer-evan** [comment]
Hey @HiddeSmit 

Thanks for your concern. This animated text slider is now dynamic. Download the latest code and enjoy it!

Also if you like this template, a star to the repository would be incredible.
