### ISSUE TITLE
custom css?

### ISSUE THREAD

**Issue by jdnguyenswin** [themefisher/timer-hugo#50]
What's the best way to make some custom changes to the css? Should I put a css file into /static? Do I need to do anything to enable that?

**Comment by jdnguyenswin** [comment]
What I mean is that, for many Hugo customisations, I understand that we're encouraged not to overwrite the original theme, but instead to put our customisations somewhere else, and those changes get priority when the site is served. 

Is that how I should make customisations to the css? Is there a preferred location for my customised css file?

**Comment by developer-evan** [comment]
Hello @jdnguyenswin 

Thanks for your concern, we have added a custom.css in our theme. please download the latest code and you will get it in `assets/css/` folder. you can write your custom CSS there.

**Comment by jdnguyenswin** [comment]
Thank you so much!
