### ISSUE TITLE
Submenu

### ISSUE THREAD

**Issue by mateusncardoso** [themefisher/timer-hugo#51]
How can I add submenu in the .css file? I cant't find in the code a place to enable hasChildren. Is there a way to do that?

**Comment by somratpro** [comment]
hello @mateusncardoso 

We listen to your feedback and added the required sub-menu HTML and CSS, now you can simply add a sub-menu from `config.toml` file. 

example code

```
[[menu.main]]
weight = 3
name = "Pages"
hasChildren = true

  [[menu.main]]
  parent = "Pages"
  name = "Career"
  url = "career"

  [[menu.main]]
  parent = "Pages"
  name = "Blog"
  url = "blog"
```

Also if you are enjoying our theme, do consider giving this theme a star, thank you
