### ISSUE TITLE
dateFormat not working

### ISSUE THREAD

**Issue by dominicpratt** [themefisher/timer-hugo#58]
Hello,

I am in the process of converting my website to Hugo using the Timer template.

Unfortunately, I did not manage to adjust the output of the date to my needs (e.g. 04.01.2022). For this I have set in config.toml

`dateFormat = "02.01.2006"`

Unfortunately this does not seem to work.

Any idea? :-)

Thanks,
Dominic

**Comment by dominicpratt** [comment]
figured it out by myself and created a pull request

**Comment by tfsomrat** [comment]
Hello @dominicpratt 

Thanks for your contribution, I merged your PR. Also, I hope you liked the themes. So a star to the repository would be very nice. have a nice day.
