### ISSUE TITLE
Social Media icon for XING is missing

### ISSUE THREAD

**Issue by tomasnorre** [themefisher/timer-hugo#6]
Hi,

Similar to twitter, linkedin etc. it would be great if the was an icon for XING.

`ion-social-xing` would be my suggestion, but don't know how to create the icon to fit your needs of a Pull Request.

https://www.xing.com/

**Comment by mehedi-sharif** [comment]
Hey @tomasnorre  , 
In timer template we used ionicons . Unfortunately they does not have any xing icon .  I would suggest you to include font awesome icon and they have xing icon in their collection . 
Thanks

**Comment by tomasnorre** [comment]
Ok. That's fine by me. Thanks for a fast reply.
