### ISSUE TITLE
Unable to display custom font in web page

### ISSUE THREAD

**Issue by danilotat** [themefisher/timer-hugo#60]
Hi,
Thanks for the precious work in developing such a good theme. 
I encounter a problem while trying to change font in the css file using a custom downloaded one. More specifically, I've uploaded inside the `/assets/css` folder my font as[ ttf | eot | woff | svg ] as suggested [here](https://blog.fontspring.com/2011/02/further-hardening-of-the-bulletproof-syntax/); then I've added the declaration inside the css as follows:

`@font-face{
	font-family: "GeosansLight";
src: url("GeosansLight.eot");
src: url("GeosansLight.eot?#iefix") format('embedded-opentype'),
url("GeosansLight.woff") format('woff'),
url("GeosansLight.ttf") format('truetype'),
url("GeosansLight.svg#svgFontName") format('svg');
}
`

Then, as I want to change just the headers with the font, I've replaced **Roboto** with **GeosansLight**  as follows:

`h1,
h2,
h3,
h4,
h5,
h6 {
  font-family: "GeosansLight", sans-serif;
}`

I'm displaying on website the websafe font, suggesting the _custom_ one isn't working. Any idea on that? Font [source](https://www.onlinewebfonts.com/download/36e6a06a4146af2f966ffcf021751724)

**Comment by tfsomrat** [comment]
Hello @danilotat 

Thanks for using our theme. Try to upload your fonts in the static folder (`static/GeosansLight.woff`). and everything looks good to me. Hope it will work

**Comment by danilotat** [comment]
Maybe I'm not understanding properly the folder structure. I'm editing the `style.css` under the folder `theme/timer-hugo/assets/css` : the src url path doesn't start from this folder, where the css is stored?

As suggested, I've uploaded fonts in the `static` folder of the website (so not the static folder under the `theme` one): I'm using the right relative path (verified by the editor), then I've rebuilt the website. It still gives me a 404 error in Chrome console. See image for details
![image](https://user-images.githubusercontent.com/36413174/150673943-64e286a3-f379-4129-8c77-97019947143c.png)

**Comment by tfsomrat** [comment]
Your font is in `fonts` folder, so your src should be `url("../fonts/GeosansLight.woff")` like this. don't need to go back this much, and don't need to mention the static folder. because when Hugo generates, the static folder will be gone and every file comes to the root folder. hope you understand.

**Comment by danilotat** [comment]
Many thanks!
