### ISSUE TITLE
Can gallery be paginated

### ISSUE THREAD

**Issue by javyxu** [themefisher/timer-hugo#62]
When I have too many  pictures, I want to set the pagination display, the current setting has no effect, I wonder if I can set it？

**Comment by tfsomrat** [comment]
Hello @javyxu 

Thanks for choosing our theme, This feature is not available on this theme, It's a big process to do. because the images don't render from content files. 

If you are interested in theme customization service, you can contact us at mehedi@themefisher.com [paid]
