### ISSUE TITLE
Error building site: Failed to load translations in file "i18n.go": failed to unmarshal i18n.go: unsupported file extension .go

### ISSUE THREAD

**Issue by deepakkabbur** [themefisher/timer-hugo#7]
Hey,
I am new to Hugo, I am trying to use the theme "timer-hugo". I am getting error 
`Error building site: Failed to load translations in file "i18n.go": failed to unmarshal i18n.go: unsupported file extension .go`

Versions:
go: 1.11
OS: Ubuntu 18.04

**Comment by divinerites** [comment]
This theme works just fine.
So you have to show your code or provide access to your repository for us to help you

**Comment by divinerites** [comment]
but sounds like your hugo is not well setup if it is a `go`error.
