### ISSUE TITLE
Client's carousel needs version upgrade

### ISSUE THREAD

**Issue by divinerites** [themefisher/timer-hugo#8]
It seems that (in section id="clients") carousel "movement" is not working anymore. Images are fine but there is no movement.

I checked css, the javascript part for "clients-logo", but can't find a solution.

Any tip, idea, solution  ??

It is also like that on the demo site.

**Comment by divinerites** [comment]
even the `nav: true` or dots: true` do not work ...

PS : again @mehedi-sharif I bought your theme as a support for your great work.

**Comment by divinerites** [comment]
well, upgrading to v2 was enough to solve it ...

**Comment by divinerites** [comment]
for the Dots, you just have to add a class `owl-theme` and use `class="owl-carousel owl-theme"`

**Comment by mehedi-sharif** [comment]
I am out of my city . By tomorrow you will get all your answers

**Comment by divinerites** [comment]
Hey, Mehedi, i got my answers :-) i can't make a PR at the moment, but :

- upgrading to layest v2
- adding `class="owl-carousel owl-theme"`

is enough to make it work.

And make it responsive :

```javascript
$("#clients-logo").owlCarousel({

        itemsCustom: false,
        pagination: false,
        items: 3,
        margin:10,
        dots: true,
        dotsEach: 3,
        loop: true,
        stagePadding: 50,
        autoplay: true,
        autoplayTimeout:1000,
        autoplayHoverPause:true,
        responsiveClass:true,
        responsive:{
            0:{
                items:2,
            },
            600:{
                items:3,
            },
            1000:{
                items:5,
            }
    }
    });
```

**Comment by mehedi-sharif** [comment]
We will make an update soon ..

**Comment by mehedi-sharif** [comment]
@divinerites , 
Update done ... Could you please the latest release .
Thanks

**Comment by divinerites** [comment]
I can't test it properly at the moment, but I quickly looked at the code, and i think @Somrat37  didn't used the latest master. `facncybox` for example is back in line.

I'll look further but some previous commits seems reverted.
